param(
	[string]$ConfigPath = "configs/third-party-source-policy.json",
	[string]$ReportPath = "docs/THIRD-PARTY-SOURCE-INVENTORY.md",
	[switch]$Enforce
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (!(Test-Path $ConfigPath)) {
	throw "Third-party source policy not found: $ConfigPath"
}

$config = Get-Content -Raw -Path $ConfigPath | ConvertFrom-Json
$trackedFiles = @(git ls-files)

$componentResults = @()
$allowedFileSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($component in $config.components) {
	$files = @(git ls-files -- $component.pattern)
	$lineSum = 0
	$byteSum = 0

	foreach ($file in $files) {
		if (Test-Path $file) {
			$allowedFileSet.Add($file) | Out-Null
			$lineSum += (Get-Content -Path $file | Measure-Object -Line).Lines

			# Use Git blob size to avoid CRLF/LF checkout differences causing policy drift on CI.
			$blobSpec = "HEAD:$file"
			$blobSizeRaw = git cat-file -s $blobSpec 2>$null
			if ($LASTEXITCODE -eq 0 -and $blobSizeRaw) {
				$byteSum += [int64]$blobSizeRaw
			} else {
				$byteSum += (Get-Item -Path $file).Length
			}
		}
	}

	$componentResults += [PSCustomObject]@{
		Name = [string]$component.name
		Pattern = [string]$component.pattern
		PreferredSource = [string]$component.preferredSource
		Status = [string]$component.status
		Reason = [string]$component.reason
		Files = [int]$files.Count
		Lines = [int]$lineSum
		Bytes = [int64]$byteSum
		MaxFiles = [int]$component.maxFiles
		MaxLines = [int]$component.maxLines
		MaxBytes = [int64]$component.maxBytes
	}
}

$totalFiles = ($componentResults | Measure-Object -Property Files -Sum).Sum
$totalLines = ($componentResults | Measure-Object -Property Lines -Sum).Sum
$totalBytes = ($componentResults | Measure-Object -Property Bytes -Sum).Sum
$generatedAt = [System.DateTimeOffset]::Now.ToString("yyyy-MM-dd HH:mm:ssK")

$largest = $componentResults | Sort-Object -Property Bytes -Descending | Select-Object -First 1

$reportLines = @(
	"# Third-Party Source Inventory",
	"",
	"Generated: $generatedAt",
	"",
	"## Summary",
	"",
	"- Components tracked: $($componentResults.Count)",
	"- Vendored files tracked: $totalFiles",
	"- Vendored lines tracked: $totalLines",
	"- Vendored bytes tracked: $totalBytes",
	"- Largest component: $($largest.Name) ($($largest.Bytes) bytes, $($largest.Lines) lines)",
	"",
	"## Component Breakdown",
	"",
	"| Component | Pattern | Status | Preferred Source | Files | Lines | Bytes | Max Files | Max Lines | Max Bytes |",
	"|---|---|---|---|---:|---:|---:|---:|---:|---:|"
)

foreach ($row in ($componentResults | Sort-Object -Property Bytes -Descending)) {
	$reportLines += "| $($row.Name) | $($row.Pattern) | $($row.Status) | $($row.PreferredSource) | $($row.Files) | $($row.Lines) | $($row.Bytes) | $($row.MaxFiles) | $($row.MaxLines) | $($row.MaxBytes) |"
}

$reportLines += ""
$reportLines += "## Policy"
$reportLines += ""
$reportLines += "- Default rule: $($config.policy.defaultRule)"
$reportLines += "- Exception rule: $($config.policy.exceptionRule)"
$reportLines += "- Blocked path regexes:"
$reportLines += ""

foreach ($pattern in $config.blockedPathRegex) {
	$reportLines += ('- `' + $pattern + '`')
}

$reportLines += ""
$reportLines += "## Notes"
$reportLines += ""
$reportLines += '- This report is generated by `scripts/audit-third-party-source.ps1`.'
$reportLines += '- Component growth beyond policy caps fails CI when `-Enforce` is used.'
$reportLines += ""

$reportDir = Split-Path -Parent $ReportPath
if (!(Test-Path $reportDir)) {
	New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

Set-Content -Path $ReportPath -Value ($reportLines -join "`r`n") -Encoding utf8

Write-Host "Generated third-party source report: $ReportPath"
Write-Host "Totals -> files: $totalFiles, lines: $totalLines, bytes: $totalBytes"

if ($Enforce) {
	$violations = @()

	foreach ($row in $componentResults) {
		if ($row.Files -gt $row.MaxFiles) {
			$violations += "$($row.Name): files $($row.Files) exceeded max $($row.MaxFiles)"
		}
		if ($row.Lines -gt $row.MaxLines) {
			$violations += "$($row.Name): lines $($row.Lines) exceeded max $($row.MaxLines)"
		}
		if ($row.Bytes -gt $row.MaxBytes) {
			$violations += "$($row.Name): bytes $($row.Bytes) exceeded max $($row.MaxBytes)"
		}
	}

	$blockedMatches = @()
	foreach ($regex in $config.blockedPathRegex) {
		$matches = @($trackedFiles | Where-Object {
			$_ -match $regex -and -not $allowedFileSet.Contains($_)
		})
		if ($matches.Count -gt 0) {
			$blockedMatches += $matches
		}
	}

	if ($blockedMatches.Count -gt 0) {
		$blockedMatches = $blockedMatches | Sort-Object -Unique
		foreach ($file in $blockedMatches) {
			$violations += "Blocked vendored source path detected: $file"
		}
	}

	if ($violations.Count -gt 0) {
		Write-Host "Third-party source policy violations:"
		$violations | ForEach-Object { Write-Host "  - $_" }
		throw "Third-party source policy check failed."
	}

	Write-Host "Third-party source policy check passed."
}
